<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ImportarEquiposSamsSeeder extends Seeder
{
    public function run(): void
    {
        // Obtener IDs de relaciones
        $tipoItemId = DB::table('tipo_items')->first()?->id;
        $sedeId = DB::table('sedes')->first()?->id;
        $bodegaId = DB::table('bodegas')->first()?->id;

        // Función para buscar uso_item_id por nombre
        $getUsoItemId = function($nombre) {
            return DB::table('uso_items')->where('nombre', 'LIKE', "%$nombre%")->value('id');
        };

        // Función para buscar estado_item_id por nombre
        $getEstadoItemId = function($nombre) {
            return DB::table('estado_items')->where('nombre', 'LIKE', "%$nombre%")->value('id');
        };

        // Función para buscar proveedor_id por nombre parcial
        $getProveedorId = function($nombre) {
            return DB::table('proveedores')->where('nombre', 'LIKE', "%$nombre%")->value('id');
        };

        // Función para buscar fabricante_id por nombre parcial  
        $getFabricanteId = function($nombre) {
            return DB::table('fabricantes')->where('nombre', 'LIKE', "%$nombre%")->value('id');
        };

        // Equipos del sistema SAMS antiguo (muestra representativa)
        $equipos = [
            [
                'codigo' => 'EWN-00701',
                'descripcion' => 'LINEA DE VIDA AUTORRETRACTIL - 20 pies (6m) de Longitud, Cable galvanizado',
                'marca' => 'MILLER MIGHTY LITE',
                'modelo' => 'RL20G-Z7',
                'vida_util' => 10,
                'fecha_fabricacion' => '2013-12-18',
                'fecha_compra' => '2014-06-17',
                'valor' => 2756300.00,
                'numero_factura' => '1639',
                'capacidades_resistencia' => 'CAP. 400 Lbs / RES. 5000 Lbs',
                'lote' => '766338',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Prevencion',
            ],
            [
                'codigo' => 'EW-00036',
                'descripcion' => 'ARNÉS MULTIPROPÓSITO DE 4 PUNTOS EN X - ANSI Z359.1',
                'marca' => 'ORBIT FALL PROTECTION SYSTEMS',
                'modelo' => 'CL0400',
                'vida_util' => 10,
                'fecha_fabricacion' => '2013-02-15',
                'fecha_compra' => '2014-01-01',
                'valor' => 133835.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => '140 KG',
                'lote' => '67179-13',
                'uso' => 'Entrenamiento',
                'estado' => 'Material Didáctico',
                'proveedor' => 'WJ RESCATE',
            ],
            [
                'codigo' => 'EWN-00488',
                'descripcion' => 'CASCO TIPO I CLASE C, LT 30 - CASCO VENTILADO CON BARBUQUEJO DE 3 PUNTOS',
                'marca' => 'ALPEN',
                'modelo' => '3 PUNTOS / PROAIR002',
                'vida_util' => 10,
                'fecha_fabricacion' => '2015-09-01',
                'fecha_compra' => '2016-07-04',
                'valor' => 155900.00,
                'numero_factura' => '4029',
                'capacidades_resistencia' => '340G',
                'lote' => 'N/A',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Honeywell',
            ],
            [
                'codigo' => 'EWB-00102',
                'descripcion' => 'ADAPTADOR DE ANCLAJE PORTÁTIL - FABRICADO EN REATA TUBULAR REFORZADA',
                'marca' => 'ORBIT FALL PROTECTION SYSTEMS',
                'modelo' => '3202P32',
                'vida_util' => 10,
                'fecha_fabricacion' => '2014-07-01',
                'fecha_compra' => '2014-10-10',
                'valor' => 41409.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'CAP. 400 LB / RES. 5000 LB',
                'lote' => '87350-14',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'WJ RESCATE',
            ],
            [
                'codigo' => 'EWB-00344',
                'descripcion' => 'MOSQUETON EN ACERO CON COMPUERTA DE TORNILLO(ROSCADO) 50 KN',
                'marca' => 'Climbing Technology',
                'modelo' => '3C476',
                'vida_util' => 10,
                'fecha_fabricacion' => '2014-10-08',
                'fecha_compra' => '2017-01-17',
                'valor' => 45000.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'RES:50 KN',
                'lote' => '114',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Deporteka',
            ],
            [
                'codigo' => 'EWN-00354',
                'descripcion' => 'ESTRANGULADOR DE POSTES - fabricada en cuerda con acoples y protección en PVC',
                'marca' => 'ORBIT FALL PROTECTION SYSTEMS',
                'modelo' => '3203R59',
                'vida_util' => 5,
                'fecha_fabricacion' => '2017-06-01',
                'fecha_compra' => '2017-09-13',
                'valor' => 35000.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'Resistencia mínima 22.2 kN (5,000 lb.)',
                'lote' => '881000',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'WJ RESCATE',
            ],
            [
                'codigo' => 'EWB-00159',
                'descripcion' => 'DESCENDEDOR I\'D L - DIÁMETRO COMPATIBLE DE CUERDA: 11,5 - 13 MM',
                'marca' => 'Petzl',
                'modelo' => 'D200LN',
                'vida_util' => 10,
                'fecha_fabricacion' => '2013-12-18',
                'fecha_compra' => '2014-05-17',
                'valor' => 710000.00,
                'numero_factura' => '1735',
                'capacidades_resistencia' => 'CAP.: 240 KG',
                'lote' => 'N/A',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Honeywell',
            ],
            [
                'codigo' => 'EWB-00407',
                'descripcion' => 'MINI ROPEGRAB BLOQUEADOR DE CUERDA CON EJE DE ESPIGA',
                'marca' => 'I.S.C.',
                'modelo' => 'RP209',
                'vida_util' => 10,
                'fecha_fabricacion' => '2012-01-01',
                'fecha_compra' => '2013-05-12',
                'valor' => 210329.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'CAP. 140 KG',
                'lote' => '23457',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'WJ RESCATE',
            ],
            [
                'codigo' => 'EW-01897',
                'descripcion' => 'TIE OFF – ESTRANGULADOR DE POSTES PARA ANCLAJE TEMPORAL',
                'marca' => 'ORBIT FALL PROTECTION SYSTEMS',
                'modelo' => '3201P71',
                'vida_util' => 10,
                'fecha_fabricacion' => '2018-07-01',
                'fecha_compra' => '2018-07-04',
                'valor' => 66197.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => '310 LBS',
                'lote' => '5238000',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'WJ RESCATE',
            ],
            [
                'codigo' => 'EWN-00103',
                'descripcion' => 'ESLINGA DE DETENCIÓN DE CAIDAS (TIPO Y) GRADUABLE EN REATA CON ABSORBEDOR',
                'marca' => 'ORBIT FALL PROTECTION SYSTEMS',
                'modelo' => '33041CPY6AL',
                'vida_util' => 5,
                'fecha_fabricacion' => '2015-07-01',
                'fecha_compra' => '2016-02-26',
                'valor' => 255200.00,
                'numero_factura' => 'WJ-625',
                'capacidades_resistencia' => 'CAP. 400 Lbs / RES:40KN',
                'lote' => '954000-15',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'WJ RESCATE',
            ],
            [
                'codigo' => 'EWB-00022',
                'descripcion' => 'ARNÉS MULTIPROPÓSITO DE CUATRO PUNTOS DE ANCLAJE EN X',
                'marca' => 'ORBIT FALL PROTECTION SYSTEMS',
                'modelo' => 'CL0400XAC',
                'vida_util' => 10,
                'fecha_fabricacion' => '2018-01-01',
                'fecha_compra' => '2017-09-08',
                'valor' => 133835.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'CAP. 400 LB / 5000 LB',
                'lote' => '87771',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'WJ RESCATE',
            ],
            [
                'codigo' => 'EWB-00323',
                'descripcion' => 'MOSQUETON EN ACERO 50 KN',
                'marca' => 'Singing Rock',
                'modelo' => 'K408',
                'vida_util' => 10,
                'fecha_fabricacion' => '2012-05-01',
                'fecha_compra' => '2013-06-01',
                'valor' => 50000.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'RES: 50 KN',
                'lote' => 'N/R',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Deporteka',
            ],
            [
                'codigo' => 'EWB-00184',
                'descripcion' => 'LÍNEA DE VIDA AUTORETRÁCTIL MILLER MIGHTY LITE 20 Ft',
                'marca' => 'HONEYWELL MILLER',
                'modelo' => 'RL20G-Z7',
                'vida_util' => 10,
                'fecha_fabricacion' => '2013-06-21',
                'fecha_compra' => '2014-07-02',
                'valor' => 2375437.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => '310 LB/5000LB',
                'lote' => 'null',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'WJ RESCATE',
            ],
            [
                'codigo' => 'EWB-00027',
                'descripcion' => 'ARNÉS DIELÉCTRICO DE CUATRO PUNTOS DE ANCLAJE EN X',
                'marca' => 'ORBIT FALL PROTECTION SYSTEMS',
                'modelo' => 'CL0400DTX',
                'vida_util' => 10,
                'fecha_fabricacion' => '2017-06-01',
                'fecha_compra' => '2017-06-05',
                'valor' => 215498.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'CAP. 400 LB / 5000 LB',
                'lote' => '1110000',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'WJ RESCATE',
            ],
            [
                'codigo' => 'EWB-00235',
                'descripcion' => 'ARRESTADOR DE CAIDA LAD-SAF X2',
                'marca' => 'DBI SALA',
                'modelo' => '6160030',
                'vida_util' => 10,
                'fecha_fabricacion' => '2017-09-01',
                'fecha_compra' => '2018-08-17',
                'valor' => 700000.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => '141 kg (310 lb)',
                'lote' => '69',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Honeywell',
            ],
            [
                'codigo' => 'EWB-00223',
                'descripcion' => 'PUÑO BLOQUEADOR PARA ASCENSOS POR CUERDA',
                'marca' => 'Petzl',
                'modelo' => 'ASCENSION/B17ALN',
                'vida_util' => 10,
                'fecha_fabricacion' => '2013-10-18',
                'fecha_compra' => '2013-12-12',
                'valor' => 196875.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'CAP. 140 KG',
                'lote' => '8061',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Dotaalturas',
            ],
            [
                'codigo' => 'EWB-00170',
                'descripcion' => 'DESCENDEDOR AUTOBLOQUEANTE DOBLE STOP',
                'marca' => 'Singing Rock',
                'modelo' => 'DSD30+25/L449102',
                'vida_util' => 10,
                'fecha_fabricacion' => '2013-01-13',
                'fecha_compra' => '2013-12-05',
                'valor' => 200000.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'CAP. 150 KG',
                'lote' => '1313',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Deporteka',
            ],
            [
                'codigo' => 'EWB-00154',
                'descripcion' => 'POLEA SENCILLA',
                'marca' => 'DINAMIK SAFETY CORP',
                'modelo' => 'S-2128',
                'vida_util' => 10,
                'fecha_fabricacion' => '2014-06-01',
                'fecha_compra' => '2016-02-15',
                'valor' => 139000.00,
                'numero_factura' => '2862',
                'capacidades_resistencia' => '30 KN',
                'lote' => 'N/A',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Honeywell',
            ],
            [
                'codigo' => 'EW-01910',
                'descripcion' => 'ESCALERA EN FIBRA DE VIDRIO SENCILLA - 8 FT 8 PASOS',
                'marca' => 'Lousville Ladder',
                'modelo' => 'FE3108',
                'vida_util' => 10,
                'fecha_fabricacion' => '2017-10-01',
                'fecha_compra' => '2018-08-09',
                'valor' => 1856000.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => '300 LBS',
                'lote' => 'N/A',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Escaleras De Colombia',
            ],
            [
                'codigo' => 'EWB-00241',
                'descripcion' => 'LINEA DE VIDA VERTICAL EN CUERDA 30 MTS - POLYESTER 100%',
                'marca' => 'ORBIT FALL PROTECTION SYSTEMS',
                'modelo' => '1125CR',
                'vida_util' => 10,
                'fecha_fabricacion' => '2016-08-01',
                'fecha_compra' => '2016-11-23',
                'valor' => 483000.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'Sistema de protección de caídas',
                'lote' => '1895000-16',
                'uso' => 'Seguridad',
                'estado' => 'En Uso',
                'proveedor' => 'WJ RESCATE',
                'es_kit' => true,
                'nombre_kit' => 'LINEA DE VIDA VERTICAL',
                'componentes_kit' => 'Cuerda de 30mts, gancho estructural, contrapeso, arrestador de caída',
            ],
            [
                'codigo' => 'EWN-00878',
                'descripcion' => 'Equipo de Autocontenido de 2.216 psi',
                'marca' => 'E.P.I.',
                'modelo' => 'N/R',
                'vida_util' => 5,
                'fecha_fabricacion' => null,
                'fecha_compra' => '2016-01-02',
                'valor' => 5000000.00,
                'numero_factura' => '1111',
                'capacidades_resistencia' => 'Presión del cilindro 2216 psig',
                'lote' => 'N/R',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Survivair',
                'es_kit' => true,
                'nombre_kit' => 'EQUIPO DE AUTOCONTENIDO',
                'componentes_kit' => 'ARNÉS-CILINDRO, REGULADOR DE PRIMERA ETAPA, MANÓMETRO-ALARMAS, REGULADOR DE SEGUNDA ETAPA, MASCARA PANORÁMICA',
            ],
            [
                'codigo' => 'EWN-00855',
                'descripcion' => 'Little Anne Adulto - Maniquí para entrenamiento RCP',
                'marca' => 'Laerdal',
                'modelo' => 'N/R',
                'vida_util' => 10,
                'fecha_fabricacion' => null,
                'fecha_compra' => '2013-08-28',
                'valor' => 620000.00,
                'numero_factura' => '1111',
                'capacidades_resistencia' => 'N/R',
                'lote' => 'N/R',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Laerdal',
            ],
            [
                'codigo' => 'EWB-00438',
                'descripcion' => 'ESTRUCTURA MULTIFUNCIONAL para entrenamiento',
                'marca' => 'I.E.T.D.H. PREVENTION WORLD QH',
                'modelo' => 'N/A',
                'vida_util' => 10,
                'fecha_fabricacion' => '2018-12-01',
                'fecha_compra' => '2018-12-01',
                'valor' => 150000000.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'N/A',
                'lote' => 'N/A',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'I.E.T.D.H. PREVENTION WORLD',
                'es_kit' => true,
                'nombre_kit' => 'ESTRUCTURA MULTIFUNCIONAL',
                'componentes_kit' => 'ESTRUCTURA MULTIFUNCIONAL #1, ESTRUCTURA MULTIFUNCIONAL #2, RETÍCULA DE POSICIONAMIENTO',
            ],
            [
                'codigo' => 'EWB-00098',
                'descripcion' => 'CUERDA SEMIESTATICA 11 MM - 50 MTS - 100% POLYESTER',
                'marca' => 'Sterling Rope',
                'modelo' => 'N/R',
                'vida_util' => 10,
                'fecha_fabricacion' => '2016-01-01',
                'fecha_compra' => '2017-08-01',
                'valor' => 350000.00,
                'numero_factura' => '123',
                'capacidades_resistencia' => 'RES: 30 KN',
                'lote' => 'N/R',
                'uso' => 'Entrenamiento',
                'estado' => 'En Uso',
                'proveedor' => 'Deporteka',
            ],
        ];

        $estadoEnUso = $getEstadoItemId('En Uso');

        foreach ($equipos as $equipo) {
            // Verificar si ya existe
            $existe = DB::table('equipos')->where('codigo', $equipo['codigo'])->exists();
            if ($existe) continue;

            DB::table('equipos')->insert([
                'tipo_item_id' => $tipoItemId,
                'codigo' => $equipo['codigo'],
                'codigo_bloqueado' => true,
                'estado_item_id' => $getEstadoItemId($equipo['estado'] ?? 'En Uso') ?? $estadoEnUso,
                'descripcion' => $equipo['descripcion'],
                'marca' => $equipo['marca'],
                'proveedor_id' => $getProveedorId($equipo['proveedor'] ?? ''),
                'fabricante_id' => $getFabricanteId($equipo['marca'] ?? ''),
                'modelo' => $equipo['modelo'],
                'sede_id' => $sedeId,
                'bodega_id' => $bodegaId,
                'vida_util' => $equipo['vida_util'],
                'fecha_fabricacion' => $equipo['fecha_fabricacion'],
                'fecha_uso' => $equipo['fecha_compra'],
                'uso_item_id' => $getUsoItemId($equipo['uso'] ?? 'Entrenamiento'),
                'es_kit' => $equipo['es_kit'] ?? false,
                'nombre_kit' => $equipo['nombre_kit'] ?? null,
                'componentes_kit' => $equipo['componentes_kit'] ?? null,
                'valor' => $equipo['valor'],
                'numero_factura' => $equipo['numero_factura'],
                'capacidades_resistencia' => $equipo['capacidades_resistencia'],
                'lote' => $equipo['lote'],
                'fecha_compra' => $equipo['fecha_compra'],
                'tiene_manual_fabricante' => false,
                'tiene_certificacion' => false,
                'tiene_imagen_general' => false,
                'tiene_imagen_etiqueta' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }

        $this->command->info('✅ Equipos importados correctamente desde SAMS antiguo.');
    }
}
