<?php

return [
    'paises' => [
        'Colombia',
        'Argentina',
        'Bolivia',
        'Brasil',
        'Chile',
        'Ecuador',
        'México',
        'Panamá',
        'Perú',
        'Venezuela',
        'España',
        'Estados Unidos',
        'Otro',
    ],

    'departamentos' => [
        'default' => ['Otro'],
        'Colombia' => [
            'Amazonas', 'Antioquia', 'Arauca', 'Atlántico', 'Bogotá D.C.', 'Bolívar', 'Boyacá',
            'Caldas', 'Caquetá', 'Casanare', 'Cauca', 'Cesar', 'Chocó', 'Córdoba', 'Cundinamarca',
            'Guainía', 'Guaviare', 'Huila', 'La Guajira', 'Magdalena', 'Meta', 'Nariño',
            'Norte de Santander', 'Putumayo', 'Quindío', 'Risaralda', 'San Andrés y Providencia',
            'Santander', 'Sucre', 'Tolima', 'Valle del Cauca', 'Vaupés', 'Vichada',
        ],
        'Argentina' => ['Otro'],
        'Bolivia' => ['Otro'],
        'Brasil' => ['Otro'],
        'Chile' => ['Otro'],
        'Ecuador' => ['Otro'],
        'México' => ['Otro'],
        'Panamá' => ['Otro'],
        'Perú' => ['Otro'],
        'Venezuela' => ['Otro'],
        'España' => ['Otro'],
        'Estados Unidos' => ['Otro'],
        'Otro' => ['Otro'],
    ],

    'municipios' => [
        'Amazonas' => ['Leticia', 'Puerto Nariño'],
        'Antioquia' => ['Medellín', 'Bello', 'Envigado', 'Itagüí', 'Apartadó', 'Turbo', 'Rionegro', 'Marinilla', 'Santuario', 'Otro'],
        'Arauca' => ['Arauca', 'Saravena', 'Fortul', 'Otro'],
        'Atlántico' => ['Barranquilla', 'Soledad', 'Malambo', 'Sabanalarga', 'Otro'],
        'Bogotá D.C.' => ['Bogotá'],
        'Bolívar' => ['Cartagena', 'Magangué', 'Turbaco', 'Otro'],
        'Boyacá' => ['Tunja', 'Duitama', 'Sogamoso', 'Chiquinquirá', 'Otro'],
        'Caldas' => ['Manizales', 'La Dorada', 'Chinchiná', 'Otro'],
        'Caquetá' => ['Florencia', 'San Vicente del Caguán', 'Otro'],
        'Casanare' => ['Yopal', 'Aguazul', 'Otro'],
        'Cauca' => ['Popayán', 'Santander de Quilichao', 'Otro'],
        'Cesar' => ['Valledupar', 'Aguachica', 'Otro'],
        'Chocó' => ['Quibdó', 'Istmina', 'Otro'],
        'Córdoba' => ['Montería', 'Sincelejo', 'Otro'],
        'Cundinamarca' => ['Soacha', 'Facatativá', 'Zipaquirá', 'Girardot', 'Chía', 'Otro'],
        'Guainía' => ['Inírida', 'Otro'],
        'Guaviare' => ['San José del Guaviare', 'Otro'],
        'Huila' => ['Neiva', 'Pitalito', 'Garzón', 'Otro'],
        'La Guajira' => ['Riohacha', 'Maicao', 'Uribia', 'Otro'],
        'Magdalena' => ['Santa Marta', 'Ciénaga', 'Fundación', 'Otro'],
        'Meta' => ['Villavicencio', 'Acacías', 'Granada', 'Otro'],
        'Nariño' => ['Pasto', 'Ipiales', 'Tumaco', 'Otro'],
        'Norte de Santander' => ['Cúcuta', 'Ocaña', 'Pamplona', 'Otro'],
        'Putumayo' => ['Mocoa', 'Puerto Asís', 'Otro'],
        'Quindío' => ['Armenia', 'Calarcá', 'La Tebaida', 'Otro'],
        'Risaralda' => ['Pereira', 'Dosquebradas', 'Santa Rosa de Cabal', 'Otro'],
        'San Andrés y Providencia' => ['San Andrés', 'Providencia', 'Otro'],
        'Santander' => ['Bucaramanga', 'Floridablanca', 'Piedecuesta', 'Barrancabermeja', 'Otro'],
        'Sucre' => ['Sincelejo', 'Corozal', 'Otro'],
        'Tolima' => ['Ibagué', 'Espinal', 'Honda', 'Otro'],
        'Valle del Cauca' => ['Cali', 'Palmira', 'Buenaventura', 'Buga', 'Tuluá', 'Cartago', 'Otro'],
        'Vaupés' => ['Mitú', 'Otro'],
        'Vichada' => ['Puerto Carreño', 'Otro'],
        'Otro' => ['Otro'],
    ],
];
